"""Kernel output fetching (leaf module extracted from KaggleService).

Small interface over two seams: plain CLI pulls (`kaggle kernels output`,
latest-only) and versioned in-process fetches (services/kaggle_versioned_output,
per-version snapshots). Orchestration that picks between versions
(download_latest_outputs, download_external_outputs) stays on KaggleService
because tests pin those seams (see tests/test_stopped_pulls.py).
"""

import asyncio
import csv
import io
import json
import logging
import os
from pathlib import Path
from typing import Any

from config import OUTPUTS_DIR, get_kaggle_cli_path

from services.account_manager import AccountManager

logger = logging.getLogger("kaggle_outputs")

VERSIONED_FETCH_TIMEOUT_SECONDS = int(
    os.getenv("VERSIONED_FETCH_TIMEOUT_SECONDS", "600")
)
# Plain `kernels output` pull has no server-side bound: a kernel that
# published gigabytes (models downloaded into /kaggle/working instead of
# scratch) stalls the stop pipeline's pre-stop snapshot forever, wedging
# the Stop button. Timeout here is non-fatal - the caller logs and
# continues to the stop-stub push.
OUTPUT_PULL_TIMEOUT_SECONDS = int(os.getenv("OUTPUT_PULL_TIMEOUT_SECONDS", "300"))


async def list_output_files(
    account_username: str, kernel_ref: str
) -> list[dict[str, Any]]:
    """Lists output files generated by the kernel run.

    Normalizes every row to {name, size, ...} and drops nameless rows
    (non-CSV CLI output like "No files found", error text, or renamed
    headers) so the files explorer never renders an undefined name.
    """
    cli = get_kaggle_cli_path()
    cmd = [cli, "kernels", "files", "-v", kernel_ref]
    env = AccountManager.get_account_env(account_username)
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )
        stdout, _stderr = await proc.communicate()
        out_str = stdout.decode("utf-8", errors="ignore")

        files = []
        if out_str and out_str.strip():
            if out_str.strip().lower() in ("no files found", "no files"):
                return []
            try:
                reader = csv.DictReader(io.StringIO(out_str))
            except Exception:
                return []
            if not reader.fieldnames:
                return []
            lowered = {(h or "").strip().lower() for h in reader.fieldnames}
            if not lowered & {"name", "filename", "file_name"}:
                return []
            for row in reader:
                if not isinstance(row, dict):
                    continue
                norm = {(k or "").strip().lower(): v for k, v in row.items()}
                name = str(
                    norm.get("name")
                    or norm.get("filename")
                    or norm.get("file_name")
                    or ""
                ).strip()
                if not name:
                    continue
                size = norm.get("size", "")
                files.append(
                    {
                        "name": name,
                        "size": size if size not in (None, "") else "N/A",
                        "creationDate": norm.get("creationdate", ""),
                    }
                )
        return files
    except Exception as e:
        logger.error(f"Failed to list output files for {kernel_ref}: {e}")
        return []


async def run_versioned_helper(
    account_username: str,
    args: list[str],
    timeout: int = VERSIONED_FETCH_TIMEOUT_SECONDS,
    ok_codes: tuple = (0,),
) -> str | None:
    """Runs the versioned-output module in-process under the account's credentials.

    Same JSON contract as the old subprocess helper; returns the payload
    string or None on any failure - best-effort enhancement, never a hard
    dependency. Blocking httpx calls run in a worker thread with a timeout.
    """
    from services import kaggle_versioned_output as _vo

    env = AccountManager.get_account_env(account_username)
    token = (env.get("KAGGLE_API_TOKEN") or "").strip()
    if not token:
        return None

    def _call() -> str:
        verb = args[0] if args else ""
        if verb == "meta" and len(args) >= 3:
            return json.dumps(
                {
                    "current_version_number": _vo.current_version(
                        args[1], args[2], token=token
                    )
                }
            )
        if verb == "fetch" and len(args) >= 5:
            saved, notes = _vo.fetch_version_output(
                args[1], args[2], int(args[3]), args[4], token=token
            )
            return json.dumps({"saved": saved, "tried": notes})
        if verb == "list" and len(args) >= 2:
            search = args[2] if len(args) > 2 else ""
            try:
                page = int(args[3]) if len(args) > 3 else 1
            except ValueError:
                page = 1
            try:
                page_size = int(args[4]) if len(args) > 4 else 20
            except ValueError:
                page_size = 20
            kernels, next_token = _vo.list_kernels(
                args[1], search, page, page_size, token=token
            )
            return json.dumps({"kernels": kernels, "nextPageToken": next_token})
        if verb == "versions" and len(args) >= 3:
            try:
                max_v = int(args[3]) if len(args) > 3 else 20
            except ValueError:
                max_v = 20
            vers = _vo.list_versions(args[1], args[2], max_v, token=token)
            cur_v = vers[0]["version"] if vers else None
            return json.dumps({"versions": vers, "current_version": cur_v})
        if verb == "log" and len(args) >= 4:
            log = _vo.fetch_version_log(args[1], args[2], int(args[3]), token=token)
            return json.dumps({"log": log})
        raise ValueError(f"unknown versioned-output verb: {args}")

    try:
        return await asyncio.wait_for(asyncio.to_thread(_call), timeout=timeout)
    except TimeoutError:
        logger.warning(
            "Versioned-output call timed out for @%s (%s)",
            account_username,
            args,
        )
        return None
    except Exception as e:
        logger.warning(f"Versioned-output call failed: {e}")
        return None


async def list_account_kernels(
    account_username: str, search: str = "", page: int = 1, page_size: int = 20
) -> dict[str, Any]:
    """Lists kernels visible to account_username via ListKernels API.

    Returns {kernels: [...], nextPageToken: str}. Each kernel has
    ref, title, slug, author, lastRunTime, currentVersionNumber etc.
    Throttled via kernel-status semaphore (same CLI weight class).
    Results are sorted reverse-chronological (recent lastRunTime first).
    """
    # Clamp to Kaggle sane limits
    page = max(1, int(page or 1))
    page_size = max(1, min(100, int(page_size or 20)))
    out = await run_versioned_helper(
        account_username,
        ["list", account_username, search or "", str(page), str(page_size)],
        timeout=120,
    )
    if not out:
        return {"kernels": [], "nextPageToken": ""}
    try:
        data = json.loads(out)
        kernels = data.get("kernels") or []

        # Reverse chronological: newest lastRunTime first
        def _time_key(k):
            return (
                k.get("lastRunTime")
                or k.get("last_run_time")
                or k.get("creationTime")
                or ""
            )

        try:
            kernels.sort(key=_time_key, reverse=True)
        except Exception:
            pass
        return {
            "kernels": kernels,
            "nextPageToken": data.get("nextPageToken") or "",
        }
    except Exception:
        return {"kernels": [], "nextPageToken": ""}


async def list_kernel_versions(
    account_username: str, kernel_ref: str, max_versions: int = 20
) -> dict[str, Any]:
    """Lists per-version snapshots for a kernel, newest first.

    Each version entry has version, label, creationTime (ISO or ""), fileCount, status, hasOutput.
    """
    owner, _, slug = kernel_ref.partition("/")
    if not owner or not slug:
        return {"versions": [], "current_version": None}
    out = await run_versioned_helper(
        account_username, ["versions", owner, slug, str(max_versions)], timeout=180
    )
    if not out:
        return {"versions": [], "current_version": None}
    try:
        data = json.loads(out)
        return {
            "versions": data.get("versions") or [],
            "current_version": data.get("current_version"),
        }
    except Exception:
        return {"versions": [], "current_version": None}


async def fetch_version_log(
    account_username: str, kernel_ref: str, version: int
) -> str:
    """Fetches log for a specific version snapshot."""
    owner, _, slug = kernel_ref.partition("/")
    if not owner or not slug:
        return ""
    out = await run_versioned_helper(
        account_username, ["log", owner, slug, str(version)], timeout=60
    )
    if not out:
        return ""
    try:
        return json.loads(out).get("log") or ""
    except Exception:
        return ""


async def get_kernel_current_version(
    account_username: str, kernel_ref: str
) -> int | None:
    """Latest pushed version number of the kernel, or None if unknown."""
    owner, _, slug = kernel_ref.partition("/")
    if not owner or not slug:
        return None
    out = await run_versioned_helper(
        account_username, ["meta", owner, slug], timeout=120
    )
    if not out:
        return None
    try:
        v = json.loads(out).get("current_version_number")
        return int(v) if v else None
    except Exception:
        return None


async def download_outputs_of_version(
    account_username: str, kernel_ref: str, version: int, run_id: str
) -> Path | None:
    """Downloads a SPECIFIC version's output snapshot into data/outputs/{run_id}.

    This recovers the partial /kaggle/working contents of cancelled or
    errored versions - which latest-only pulls miss once a stop-stub or a
    newer push becomes the kernel's latest version.
    """
    owner, _, slug = kernel_ref.partition("/")
    if not owner or not slug:
        return None
    target_dir = OUTPUTS_DIR / str(run_id)
    target_dir.mkdir(parents=True, exist_ok=True)
    # rc 0 = files saved; rc 3 = version finalized but published nothing
    out = await run_versioned_helper(
        account_username,
        ["fetch", owner, slug, str(version), str(target_dir)],
        ok_codes=(0, 3),
    )
    if not out:
        return None
    try:
        parsed = json.loads(out)
        saved = parsed.get("saved", [])
        notes = parsed.get("tried") or []
        if notes:
            logger.info(
                f"Version {version} output probe for {run_id}: " + "; ".join(notes)
            )
    except Exception:
        saved = []
    if not saved:
        return None
    logger.info(f"Version {version} output for {run_id}: saved {len(saved)} file(s).")
    return target_dir


async def download_outputs(account_username: str, kernel_ref: str, run_id: str) -> Path:
    """Downloads all output files to `data/outputs/{run_id}`."""
    from services import kaggle_service as _ksmod  # lazy: test-pinned seam

    timeout = _ksmod.OUTPUT_PULL_TIMEOUT_SECONDS
    target_dir = OUTPUTS_DIR / run_id
    target_dir.mkdir(parents=True, exist_ok=True)

    cli = get_kaggle_cli_path()
    # NOTE: kernel ref must be the positional argument; `-o` is a boolean
    # force flag in kaggle CLI >= 2.x (not a value-taking option).
    cmd = [cli, "kernels", "output", kernel_ref, "-p", str(target_dir), "-o"]
    env = AccountManager.get_account_env(account_username)

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env=env,
    )
    try:
        _stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except TimeoutError:
        try:
            proc.kill()
        except Exception:
            pass
        raise RuntimeError(f"kaggle kernels output timed out after {timeout}s")
    if proc.returncode != 0:
        err_tail = stderr.decode("utf-8", errors="ignore").strip()[-500:]
        raise RuntimeError(
            f"kaggle kernels output failed (rc={proc.returncode}): {err_tail}"
        )
    return target_dir
