import os
import json
import uuid
import asyncio
import logging
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional, Union, Set
from app.services.kaggle_service import KaggleService
from app.database import create_distributed_workload, update_workload_status, utcnow_iso
from app.config import LOGS_DIR

logger = logging.getLogger("workload_distributor")

# Global throttle for distributed pushes: without this, 16 accounts *2 sessions
# = 32 shards launch 16 pushes in parallel at t=0 -> ~2GB RAM spike -> OOM killer
# does `killed uvicorn`. Limit mirrors KaggleService.PUSH_CONCURRENCY.
DISTRIBUTED_PUSH_CONCURRENCY = max(1, int(os.getenv("DISTRIBUTED_PUSH_CONCURRENCY", "3")))
STATUS_CHECK_CONCURRENCY = max(1, int(os.getenv("DISTRIBUTED_STATUS_CONCURRENCY", "3")))

class WorkloadDistributor:
    @staticmethod
    def inject_shard_config_into_notebook(
        code_content: str,
        filename: str,
        shard_id: int,
        total_shards: int,
        start_index: int,
        end_index: int,
        total_items: int,
        custom_params: Optional[Dict[str, Any]] = None
    ) -> str:
        """Injects shard parameters at the top of the .ipynb or .py code."""
        custom_json = json.dumps(custom_params or {})
        header_code = (
            "# ==========================================\n"
            "# AUTO-INJECTED WORKLOAD SHARD CONFIGURATION\n"
            "# Generated by Kaggle Automation Dashboard\n"
            "# ==========================================\n"
            f"SHARD_ID = {shard_id}\n"
            f"TOTAL_SHARDS = {total_shards}\n"
            f"START_INDEX = {start_index}\n"
            f"END_INDEX = {end_index}\n"
            f"TOTAL_ITEMS = {total_items}\n"
            f"SHARD_PARAMS = {custom_json}\n\n"
            f"print(f'🚀 [DISTRIBUTED RUN] Shard {{SHARD_ID + 1}}/{{TOTAL_SHARDS}}: processing range [{{START_INDEX}} -> {{END_INDEX}}] of {{TOTAL_ITEMS}} total')\n"
            "# ==========================================\n"
        )

        if filename.endswith(".ipynb"):
            try:
                nb_dict = json.loads(code_content)
                shard_cell = {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {"tags": ["kaggle-automation-shard-config"]},
                    "outputs": [],
                    "source": [line + "\n" for line in header_code.splitlines()]
                }
                # Prepend to cells
                nb_dict["cells"] = [shard_cell] + nb_dict.get("cells", [])
                return json.dumps(nb_dict, indent=2)
            except Exception as e:
                logger.error(f"Failed to parse notebook JSON, prepending header directly: {e}")
                return header_code + "\n" + code_content
        else:
            return header_code + "\n" + code_content

    # ------------------------------------------------------------------
    # Availability / runner-plan helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _is_gpu(accelerator: Optional[str]) -> bool:
        return bool(accelerator) and str(accelerator).lower() not in ("none", "default", "cpu")

    @classmethod
    async def _busy_gpu_sessions(cls, accounts: List[str], launch_is_gpu: bool) -> Dict[str, int]:
        """Counts busy GPU session slots per account.

        Queries live Kaggle status for active (queued/running) GPU runs in the DB.
        If a kernel is complete, error, or stopped, its DB record is reaped
        and its slot freed immediately. Genuinely active (running/queued)
        kernels consume 1 slot per distinct kernel_ref.

        Throttled to STATUS_CHECK_CONCURRENCY parallel `kaggle kernels status`
        calls so 16 accounts with 30+ active runs don't spawn 30 CLI processes
        at once (the same OOM that kills pushes).
        """
        from datetime import datetime, timezone
        from app.database import get_active_runs, update_run_status, utcnow_iso

        busy: Dict[str, Set[str]] = {a: set() for a in accounts}
        if not launch_is_gpu:
            return {a: 0 for a in accounts}

        account_set = set(accounts)

        # Collect candidates first (sync DB scan)
        candidates = []
        for r in get_active_runs():
            acc = r.get("account_username")
            if acc not in account_set:
                continue
            if not cls._is_gpu(r.get("accelerator")):
                continue
            candidates.append(r)

        if not candidates:
            return {a: 0 for a in accounts}

        sem = asyncio.Semaphore(STATUS_CHECK_CONCURRENCY)

        async def check_one(row):
            async with sem:
                resp = await KaggleService.get_kernel_status(row["account_username"], row["kernel_ref"])
            return row, resp.get("status", "unknown")

        results = await asyncio.gather(*[check_one(r) for r in candidates])

        for row, st in results:
            if st in ("complete", "error", "stopped", "cancelacknowledged"):
                update_run_status(row["id"], "stopped" if "cancel" in st else st, "auto-reaped by availability check", utcnow_iso())
                continue
            busy[row["account_username"]].add(row["kernel_ref"])

        return {a: len(busy[a]) for a in accounts}

    MAX_GPU_SESSIONS_PER_ACCOUNT = 2  # Kaggle's batch GPU session cap

    @classmethod
    def _normalize_sessions_map(
        cls,
        sessions_per_account: Union[int, Dict[str, int], None],
        accounts: List[str]
    ) -> Dict[str, int]:
        """Accepts a global count OR per-account overrides {username: 1|2}.

        Per-account values are clamped to Kaggle's 1..2 batch-GPU range;
        accounts missing from the map fall back to the global default of 2.
        """
        if isinstance(sessions_per_account, dict):
            default = max(1, min(cls.MAX_GPU_SESSIONS_PER_ACCOUNT, 2))
            out = {a: default for a in accounts}
            for acc, val in sessions_per_account.items():
                if acc in out:
                    try:
                        out[acc] = max(1, min(cls.MAX_GPU_SESSIONS_PER_ACCOUNT, int(val)))
                    except (TypeError, ValueError):
                        continue
            return out
        try:
            n = int(sessions_per_account if sessions_per_account is not None else 2)
        except (TypeError, ValueError):
            n = 2
        n = max(1, min(cls.MAX_GPU_SESSIONS_PER_ACCOUNT, n))
        return {a: n for a in accounts}

    @classmethod
    def _build_runner_plan(
        cls,
        accounts: List[str],
        sessions_map: Dict[str, int],
        accelerator: str,
        busy: Dict[str, int]
    ) -> List[Dict[str, Any]]:
        """Expands accounts into runners based on free slots (silent reduction).

        Account capacity is Kaggle's hard limit of 2 concurrent GPU sessions:
        free = max(0, 2 - busy); effective = min(chosen, free). CPU launches
        aren't capped by that limit at all. `chosen` comes from the per-account
        sessions map (which may itself be a uniform global value).
        """
        gpu_launch = cls._is_gpu(accelerator)
        plan = []
        for a in accounts:
            chosen = sessions_map.get(a, 2)
            b = busy.get(a, 0)
            if gpu_launch:
                free = max(0, cls.MAX_GPU_SESSIONS_PER_ACCOUNT - b)
                effective = min(chosen, free)
            else:
                effective = chosen
            plan.append({
                "account": a,
                "requested": chosen,
                "busy": b,
                "slots": effective
            })
        return plan

    RECLAIM_WINDOW_MINUTES = 30  # how far back we look for slot-holding kernels

    @classmethod
    async def reclaim_slots(cls, accounts: List[str]) -> Dict[str, Any]:
        """Actively hunts GPU slot-holders on the given accounts and cancels them.

        Kaggle keeps a stopped session's slot occupied while the worker tears
        down (CANCEL_ACKNOWLEDGED can persist for many minutes). Instead of
        waiting passively, we find dashboard-managed kernels that are still
        RUNNING/QUEUED and push a cancel stub to each one.

        Safety: only kernel_refs that exist in our DB are touched - foreign
        kernels are reported as warnings, never auto-cancelled.
        """
        from datetime import datetime, timedelta
        from app.database import get_all_runs, get_run_by_id
        from app.services.kaggle_service import KaggleService

        cutoff = datetime.now(timezone.utc) - timedelta(minutes=cls.RECLAIM_WINDOW_MINUTES)
        candidates: Dict[str, List[Dict[str, Any]]] = {a: [] for a in accounts}
        seen_refs = set()

        for r in get_all_runs(limit=200):
            acc = r.get("account_username")
            if acc not in candidates:
                continue
            if not cls._is_gpu(r.get("accelerator")):
                continue
            if r["id"] in seen_refs:
                continue
            stamp = r.get("end_time") or r.get("start_time") or ""
            try:
                when = datetime.fromisoformat(str(stamp))
                if when.tzinfo is None:
                    when = when.replace(tzinfo=timezone.utc)
                if when < cutoff:
                    continue
            except Exception:
                pass  # unparsable stamp - keep as candidate rather than miss it
            seen_refs.add(r["id"])
            candidates[acc].append(r)

        cancelled, already_gone, warnings = [], [], []

        # Check statuses with limited concurrency (reclaim can touch 200 rows)
        sem = asyncio.Semaphore(STATUS_CHECK_CONCURRENCY)
        stop_sem = asyncio.Semaphore(DISTRIBUTED_PUSH_CONCURRENCY)

        async def check_and_maybe_stop(acc: str, row: Dict[str, Any]):
            async with sem:
                resp = await KaggleService.get_kernel_status(acc, row["kernel_ref"])
            st = resp.get("status", "unknown")
            if st in ("complete", "error", "stopped", "cancelacknowledged"):
                return ("gone", {"ref": row["kernel_ref"], "status": st})
            run_row = get_run_by_id(row["id"])
            if not run_row:
                return ("warn", {"ref": row["kernel_ref"], "status": st, "error": "run not found"})
            # stop_kernel itself pushes a stub (heavy) - throttle too
            async with stop_sem:
                stop = await KaggleService.stop_kernel(row["id"])
            if stop.get("success"):
                return ("cancelled", {"ref": row["kernel_ref"], "was": st})
            return ("warn", {"ref": row["kernel_ref"], "status": st, "error": stop.get("error", "stop failed")})

        # Flatten candidates into tasks
        tasks = []
        for acc in accounts:
            for row in candidates[acc]:
                tasks.append(check_and_maybe_stop(acc, row))

        if tasks:
            results = await asyncio.gather(*tasks)
            for kind, payload in results:
                if kind == "cancelled":
                    cancelled.append(payload)
                elif kind == "gone":
                    already_gone.append(payload)
                else:
                    warnings.append(payload)

        return {"cancelled": cancelled, "already_free": already_gone, "warnings": warnings}

    @classmethod
    async def distribute_and_launch(
        cls,
        base_title: str,
        code_content: str,
        filename: str,
        accounts: List[str],
        total_items: int,
        start_offset: int = 0,
        accelerator: str = "none",
        enable_internet: bool = True,
        is_trial: bool = False,
        timeout_seconds: Optional[int] = None,
        env_vars: Optional[Dict[str, Any]] = None,
        sessions_per_account: Union[int, Dict[str, int]] = 2,
        manual_shards: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        """Partitions the workload across expanded per-account GPU runners.

        Each account may run up to its `sessions_per_account` value (1..2)
        concurrent GPU sessions - pass an int for a uniform setting or a dict
        {username: count} for per-account control. If `manual_shards` is
        supplied, custom ranges and account assignments are honored directly.
        Availability is checked live and validated atomically BEFORE any
        workload record is created.
        """
        accounts = [a for a in accounts if a]
        if manual_shards:
            if len(manual_shards) == 0:
                return {"success": False, "error": "At least one manual shard must be specified."}
            for i, ms in enumerate(manual_shards):
                acc = ms.get("account")
                if not acc:
                    return {"success": False, "error": f"Manual shard #{i + 1} is missing a target Kaggle account."}
                if acc not in accounts:
                    accounts.append(acc)

        if not accounts:
            return {"success": False, "error": "No Kaggle accounts selected for distribution."}
        sessions_map = cls._normalize_sessions_map(sessions_per_account, accounts)

        # 0. Actively reclaim GPU slots: find lingering dashboard-managed
        #    kernels (RUNNING/QUEUED long after their run "ended") and cancel
        #    them instead of failing with Kaggle's session-cap error.
        if cls._is_gpu(accelerator):
            try:
                reclaim = await cls.reclaim_slots(accounts)
                if reclaim["cancelled"]:
                    logger.warning(
                        f"Reclaimed {len(reclaim['cancelled'])} lingering GPU "
                        f"session(s): {[c['ref'] for c in reclaim['cancelled']]}"
                    )
                    await asyncio.sleep(15)  # give cancellations a moment to propagate
            except Exception as e:
                logger.warning(f"Slot reclamation skipped: {e}")

        # 1. Live availability check
        busy = await cls._busy_gpu_sessions(accounts, cls._is_gpu(accelerator))

        workload_id = f"workload_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"

        if manual_shards:
            # Validate manual shards
            if len(manual_shards) == 0:
                return {"success": False, "error": "At least one manual shard must be specified."}

            shards_info = []
            for i, ms in enumerate(manual_shards):
                acc = ms.get("account")
                if not acc:
                    return {"success": False, "error": f"Manual shard #{i + 1} is missing a target Kaggle account."}
                try:
                    s_idx = int(ms.get("start_index", 0))
                    e_idx = int(ms.get("end_index", 0))
                except (ValueError, TypeError):
                    return {"success": False, "error": f"Manual shard #{i + 1} has invalid start/end indices."}
                if s_idx > e_idx:
                    return {"success": False, "error": f"Manual shard #{i + 1} has start index ({s_idx}) greater than end index ({e_idx})."}
                shards_info.append({
                    "shard_index": i,
                    "account_username": acc,
                    "start_index": s_idx,
                    "end_index": e_idx,
                    "count": max(0, e_idx - s_idx),
                    "custom_params": ms.get("custom_params")
                })

            # Check per-account GPU slot capacity in manual mode
            if cls._is_gpu(accelerator):
                for acc in set(s["account_username"] for s in shards_info):
                    assigned = sum(1 for s in shards_info if s["account_username"] == acc)
                    active_sess = busy.get(acc, 0)
                    if assigned + active_sess > 2:
                        return {
                            "success": False,
                            "error": f"Account @{acc} has {active_sess} active GPU session(s) and cannot run {assigned} manual shards (Kaggle cap is 2 concurrent GPU sessions)."
                        }

            R = len(shards_info)
            total_units = sum(s["count"] for s in shards_info)
            workload_type = "manual_range"
            plan = [{"account": acc, "slots": sum(1 for s in shards_info if s["account_username"] == acc), "busy": busy.get(acc, 0)} for acc in accounts]

        else:
            # Automatic uniform partition
            plan = cls._build_runner_plan(accounts, sessions_map, accelerator, busy)
            runners: List[Dict[str, Any]] = []
            for p in plan:
                for _ in range(p["slots"]):
                    runners.append({"account": p["account"]})

            R = len(runners)
            if R == 0:
                detail = ", ".join(f"@{p['account']}: {p['busy']} active" for p in plan)
                return {
                    "success": False,
                    "error": f"No free GPU session slots. Active sessions - {detail}. "
                             "Stop existing runs or wait for them to finish."
                }

            if total_items < R:
                return {"success": False, "error": f"Cannot split {total_items} items across {R} runners (fewer items than shards)."}

            workload_type = "range"
            total_units = total_items
            chunk_size = total_units // R
            remainder = total_units % R

            shards_info = []
            current_start = start_offset
            for i, runner in enumerate(runners):
                extra = 1 if i < remainder else 0
                current_chunk = chunk_size + extra
                current_end = current_start + current_chunk
                shards_info.append({
                    "shard_index": i,
                    "account_username": runner["account"],
                    "start_index": current_start,
                    "end_index": current_end,
                    "count": current_chunk
                })
                current_start = current_end

        # 3. Atomic pre-flight: every planned kernel_ref must be free BEFORE
        #    the workload row exists (zero side effects on rejection).
        from app.database import get_active_runs as db_active_runs
        active_refs = {r["kernel_ref"] for r in db_active_runs()}
        planned_conflicts = []
        for s in shards_info:
            shard_title = f"{base_title} [Shard {s['shard_index'] + 1}/{R}]"
            ref = f"{s['account_username']}/{KaggleService.sanitize_slug(shard_title[:50])}"
            if ref in active_refs:
                planned_conflicts.append(ref)
        if planned_conflicts:
            return {
                "success": False,
                "status": "conflict",
                "error": ("Kernel(s) already active with the same title: "
                          + ", ".join(sorted(set(planned_conflicts)))
                          + ". Use a different base title or stop those runs first.")
            }

        # 4. Commit workload row only after validation passed
        create_distributed_workload({
            "id": workload_id,
            "title": base_title,
            "workload_type": workload_type,
            "total_units": total_units,
            "accounts_used": json.dumps({
                "accounts": list(dict.fromkeys(accounts)),
                "runners": [{"account": s["account_username"], "shard_index": s["shard_index"]} for s in shards_info],
                "sessions_per_account": sessions_map,
                "is_manual": bool(manual_shards)
            }),
            "created_at": utcnow_iso(),
            "status": "running"
        })

        # 4b. One-time log purge for this batch BEFORE any shard writes.
        # Per-shard purge raced when 16-32 shards launched in parallel (each
        # shard deleted logs just created by its peers). Do it once here.
        try:
            LOGS_DIR.mkdir(parents=True, exist_ok=True)
            os.environ["_WORKLOAD_PURGE_DONE"] = "1"
            KaggleService._purge_previous_logs()
            logger.info(f"Workload {workload_id}: purged logs once for {R} shards")
        except Exception as e:
            logger.warning(f"Workload {workload_id}: log purge skipped: {e}")

        # 5. Launch: throttled across accounts, staggered within an account
        # Without throttle, 16 accounts *2 sessions = 16 concurrent
        # `kaggle kernels push` at t=0 -> 2GB spike -> `killed uvicorn`.
        # push_sem caps global concurrent pushes to DISTRIBUTED_PUSH_CONCURRENCY.
        push_sem = asyncio.Semaphore(DISTRIBUTED_PUSH_CONCURRENCY)

        async def launch_shard(shard: Dict[str, Any]):
            idx = shard["shard_index"]
            account = shard["account_username"]
            shard_title = f"{base_title} [Shard {idx + 1}/{R}]"

            injected_code = cls.inject_shard_config_into_notebook(
                code_content=code_content,
                filename=filename,
                shard_id=idx,
                total_shards=R,
                start_index=shard["start_index"],
                end_index=shard["end_index"],
                total_items=total_units,
                custom_params=shard.get("custom_params")
            )

            async with push_sem:
                result = await KaggleService.push_kernel(
                    account_username=account,
                    title=shard_title,
                    code_content=injected_code,
                    filename=filename,
                    accelerator=accelerator,
                    enable_internet=enable_internet,
                    is_trial=is_trial,
                    timeout_seconds=timeout_seconds,
                    env_vars=env_vars,
                    workload_id=workload_id,
                    shard_index=idx,
                    total_shards=R
                )
            return {
                "shard_index": idx,
                "account": account,
                "range": [shard["start_index"], shard["end_index"]],
                "count": shard["count"],
                "push_result": result
            }

        by_account: Dict[str, List[Dict[str, Any]]] = {}
        for s in shards_info:
            by_account.setdefault(s["account_username"], []).append(s)

        stagger_seconds = int(os.getenv("INTER_PUSH_STAGGER_SECONDS", "20"))

        async def launch_account_group(acc: str, group: List[Dict[str, Any]]):
            out = []
            for j, s in enumerate(group):
                if j > 0 and stagger_seconds > 0:
                    await asyncio.sleep(stagger_seconds)  # stagger same-account pushes - Kaggle session cap needs time to settle between pushes
                out.append(await launch_shard(s))
            return out

        try:
            grouped = await asyncio.gather(
                *[launch_account_group(acc, group) for acc, group in by_account.items()],
                return_exceptions=True
            )
        finally:
            os.environ.pop("_WORKLOAD_PURGE_DONE", None)

        processed_results = []
        for group_result in grouped:
            if isinstance(group_result, Exception):
                processed_results.append({"error": str(group_result)})
                continue
            for r in group_result:
                processed_results.append(r if not isinstance(r, Exception) else {"error": str(r)})

        pushed_ok = sum(
            1 for r in processed_results
            if isinstance(r, dict) and r.get("push_result", {}).get("success")
        )
        if pushed_ok == R:
            final_status = "dispatched"
        elif pushed_ok > 0:
            final_status = "partial"
        else:
            final_status = "failed"
        update_workload_status(workload_id, final_status)

        return {
            "success": pushed_ok > 0,
            "workload_id": workload_id,
            "base_title": base_title,
            "total_units": total_units,
            "total_shards": R,
            "sessions_per_account": sessions_map,
            "runner_plan": plan,
            "shards_pushed": pushed_ok,
            "status": final_status,
            "shards": processed_results
        }
