import json
import uuid
import asyncio
import logging
from datetime import datetime
from typing import List, Dict, Any, Optional
from app.services.kaggle_service import KaggleService
from app.database import create_distributed_workload

logger = logging.getLogger("workload_distributor")

class WorkloadDistributor:
    @staticmethod
    def inject_shard_config_into_notebook(
        code_content: str,
        filename: str,
        shard_id: int,
        total_shards: int,
        start_index: int,
        end_index: int,
        total_items: int,
        custom_params: Optional[Dict[str, Any]] = None
    ) -> str:
        """Injects shard parameters at the top of the .ipynb or .py code."""
        custom_json = json.dumps(custom_params or {})
        header_code = (
            "# ==========================================\n"
            "# AUTO-INJECTED WORKLOAD SHARD CONFIGURATION\n"
            "# Generated by Kaggle Automation Dashboard\n"
            "# ==========================================\n"
            f"SHARD_ID = {shard_id}\n"
            f"TOTAL_SHARDS = {total_shards}\n"
            f"START_INDEX = {start_index}\n"
            f"END_INDEX = {end_index}\n"
            f"TOTAL_ITEMS = {total_items}\n"
            f"SHARD_PARAMS = {custom_json}\n\n"
            f"print(f'🚀 [DISTRIBUTED RUN] Shard {{SHARD_ID + 1}}/{{TOTAL_SHARDS}}: processing range [{{START_INDEX}} -> {{END_INDEX}}] of {{TOTAL_ITEMS}} total')\n"
            "# ==========================================\n"
        )

        if filename.endswith(".ipynb"):
            try:
                nb_dict = json.loads(code_content)
                shard_cell = {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {"tags": ["kaggle-automation-shard-config"]},
                    "outputs": [],
                    "source": [line + "\n" for line in header_code.splitlines()]
                }
                # Prepend to cells
                nb_dict["cells"] = [shard_cell] + nb_dict.get("cells", [])
                return json.dumps(nb_dict, indent=2)
            except Exception as e:
                logger.error(f"Failed to parse notebook JSON, prepending header directly: {e}")
                return header_code + "\n" + code_content
        else:
            return header_code + "\n" + code_content

    @classmethod
    async def distribute_and_launch(
        cls,
        base_title: str,
        code_content: str,
        filename: str,
        accounts: List[str],
        total_items: int,
        start_offset: int = 0,
        accelerator: str = "none",
        enable_internet: bool = True,
        is_trial: bool = False,
        timeout_seconds: Optional[int] = None
    ) -> Dict[str, Any]:
        """Calculates workload partitions across accounts and dispatches them concurrently."""
        num_accounts = len(accounts)
        if num_accounts == 0:
            return {"success": False, "error": "No Kaggle accounts selected for distribution."}

        workload_id = f"workload_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"
        
        # Calculate shard partitions
        total_units = total_items
        chunk_size = total_units // num_accounts
        remainder = total_units % num_accounts

        shards_info = []
        current_start = start_offset

        for i in range(num_accounts):
            extra = 1 if i < remainder else 0
            current_chunk = chunk_size + extra
            current_end = current_start + current_chunk
            
            shards_info.append({
                "shard_index": i,
                "account_username": accounts[i],
                "start_index": current_start,
                "end_index": current_end,
                "count": current_chunk
            })
            current_start = current_end

        # Save workload to database
        create_distributed_workload({
            "id": workload_id,
            "title": base_title,
            "workload_type": "range",
            "total_units": total_units,
            "accounts_used": json.dumps(accounts),
            "created_at": datetime.utcnow().isoformat(),
            "status": "running"
        })

        # Launch all shards in parallel
        async def launch_shard(shard: Dict[str, Any]):
            idx = shard["shard_index"]
            account = shard["account_username"]
            shard_title = f"{base_title} [Shard {idx + 1}/{num_accounts}]"
            
            # Inject shard variables
            injected_code = cls.inject_shard_config_into_notebook(
                code_content=code_content,
                filename=filename,
                shard_id=idx,
                total_shards=num_accounts,
                start_index=shard["start_index"],
                end_index=shard["end_index"],
                total_items=total_units
            )

            result = await KaggleService.push_kernel(
                account_username=account,
                title=shard_title,
                code_content=injected_code,
                filename=filename,
                accelerator=accelerator,
                enable_internet=enable_internet,
                is_trial=is_trial,
                timeout_seconds=timeout_seconds,
                workload_id=workload_id,
                shard_index=idx,
                total_shards=num_accounts
            )
            return {
                "shard_index": idx,
                "account": account,
                "range": [shard["start_index"], shard["end_index"]],
                "count": shard["count"],
                "push_result": result
            }

        launch_tasks = [launch_shard(s) for s in shards_info]
        shard_results = await asyncio.gather(*launch_tasks, return_exceptions=True)

        processed_results = []
        for r in shard_results:
            if isinstance(r, Exception):
                processed_results.append({"error": str(r)})
            else:
                processed_results.append(r)

        return {
            "success": True,
            "workload_id": workload_id,
            "base_title": base_title,
            "total_units": total_units,
            "total_shards": num_accounts,
            "shards": processed_results
        }
